#On se met en sudo
sudo: required

#On dit a travis qu on a besoin de dockerd
services:
  - docker

before_install:
  - docker build -t damnda/docker-react-test -f ./client/Dockerfile.dev ./client

#-- --coverage just for exit on a le coverage  
script:
  - docker run -e CI=true damnda/docker-react-test npm run test -- --coverage
after_success:
#Build each production docker image
 - docker build -t damnda/multiclient ./client 
 - docker build -t damnda/multinginx ./nginx 
 - docker build -t damnda/multiserver ./server 
 - docker build -t damnda/multiworker ./worker 
# Log in to the docker CLI echo parce que le password est interactif
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#Take those images and push to docker hub
 - docker push damnda/multiclient
 - docker push damnda/multinginx
 - docker push damnda/multiserver
 - docker push damnda/multiworker